### ISSUE TITLE
etcd profile out of sync, doesn't seem to get fixed

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#571] opened 2015-05-20 00:44 UTC
Ran an FV run on the bobcat rig 

* using my smc-multi-pids branch, which supports multiple neutron workers, 
* bobcat rig was patched with calico master commit d649e65
* running 8 API workers on the control node

The FV run failed: http://calicobobcat-jenkins.gulfstream:8080/job/fv-tests/791/.  The test_security_group failures seem to be genuine ping failures.  

I manually ran the I ran test_security_group from the command line and paused the test when pings started to fail.

It looks like horizon's picture of the group2 SG differs from that in etcd.  In horizon, it has an allow rule from the default group; in etcd that is missing.  I'm not sure how that got out of sync but the periodic resync doesn't seem to fix it.

**Comment by fasaxc** [comment] 2015-05-20 01:50
Re-ran that same test and it looked like it was working before I left the office.  Still, pretty worrying to get two failures in a row.

**Comment by fasaxc** [comment] 2015-05-20 01:51
From code reading, it looks like that test should re-add the rule at the start of the test so I'm not sure how it could fail twice in a row if that re-add was giving us a kick to re-write the profile.

**Comment by Lukasa** [comment] 2015-05-20 05:47
Periodic resync won't fix this at the moment, it's a known problem.

What's on the smc-multi-pids branch?

**Comment by Lukasa** [comment] 2015-05-20 05:47
Also, when testing this, make sure to watch the relevant key in etcd. I wonder if we're having a write ordering problem.

**Comment by matthewdupre** [comment] 2015-05-20 09:42
@Lukasa - what do you think the known problem is?

**Comment by Lukasa** [comment] 2015-05-20 10:14
We don't update existing keys during re sync, we either write missing ones or delete extra ones.

**Comment by matthewdupre** [comment] 2015-05-20 10:24
OK, understood - am I right in inferring that you don't know what the original cause of this is (other than potentially writes overtaking each other)?

**Comment by Lukasa** [comment] 2015-05-20 12:10
Correct.

**Comment by fasaxc** [comment] 2015-05-20 15:23
My branch is in calico-test. It fixes some tests that were asserting that there was only one neutron process.

**Comment by fasaxc** [comment] 2015-05-20 15:24
I've been running with 8 workers

**Comment by ed-harrison** [comment] 2015-06-05 10:46
@Lukasa This is currently with you.  Are you actively thinking about how we could modify our resync strategy to catch cases where the keys are present, but incorrect?

**Comment by Lukasa** [comment] 2015-06-05 10:47
Depends what you mean by actively. I have a number of ways to fix this, but I don't know what the urgency on them is. We should discuss on Monday.

**Comment by ed-harrison** [comment] 2015-06-05 12:53
Indeed...

**Comment by matthewdupre** [comment] 2015-06-10 09:56
The original cause of this could perhaps be issue #635?

There's still the question of improving the resync to actually refresh the security groups though.

**Comment by Lukasa** [comment] 2015-06-15 10:26
Please note this is still not fixed, but the cause of *this specific instance* of the issue is fixed.

**Comment by Lukasa** [comment] 2015-07-16 08:01
The fix for this is now merged.

**Closed by Lukasa** 2015-07-16 08:01 UTC
Labels: bug, neutron driver
