### ISSUE TITLE
Randomly, some Felix launches fail to register with the plugin.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#54] opened 2014-11-28 16:44 UTC
While playing with install repeatedly today working on charms, I found myself with a Felix that was running happily and a plugin that thought it wasn't running at all (admin state down). This prevented VM boot because Felix never got told about the VMs coming up so it never provided routing for them.

This goes away if Felix is restarted: the plugin immediately notices Felix and informs it of all of its VMs, which can then merrily reboot.

This is tricky as hell to reproduce it and I don't know quite what the repro scenario is, besides the fact that charmed installs can do so. Given that charms kind of install everything at once it's possible it's a weird ordering issue. One thing that might be relevant is that my Horizon dashboard lists an OVS agent for that machine that is also listed as 'up', though it isn't in use. Can't tell how important that is though at this time.

**Comment by plwhite** [comment] 2015-01-19 14:45
I am going to close this as a duplicate of issue #110, which would have the exact same symptoms and has now been fixed.

**Closed by plwhite** 2015-01-19 14:45 UTC
Labels: bug
