### ISSUE TITLE
Default route gets created to an ns-* device

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#462] opened 2015-04-27 15:36 UTC
When setting up a pure L3-routed system (i.e. compute hosts connected directly to routers), we found we needed to set up a default route for the VM networks to avoid AS puddling.  However, it seems that a default route already exists to an ns-* device. 

Deleting that default route and adding a new one via the correct interface worked round the problem for me, but obviously this won't survive reboot.

Is there anything better we can do?  Why does this route to the ns interface exist anyway?

**Comment by fasaxc** [comment] 2015-04-28 02:55
One of our active lab trials needs a persistent solution to this one.  I think we need to solve it soon.

**Comment by fasaxc** [comment] 2015-04-28 02:57
@neiljerram please can you triage this to the right person?  I think the ns-* interface comes from the DHCP agent.

**Comment by Lukasa** [comment] 2015-04-28 07:43
> Why does this route to the ns interface exist anyway?

The route exists because the dummy interface is created with a given IP address and subnet. The Linux kernel therefore assumes it can reach that subnet out that interface, so it also creates the route.

At this point in time I don't know of any way to prevent that route creation event from occurring.

**Comment by lwr20** [comment] 2015-04-28 07:59
I'm assuming its us creating the interface, yes?  If so, do we ever need the route?  And if not, can we add code just after the creation to delete the route?

**Comment by neiljerram** [comment] 2015-04-28 08:19
No, we certainly never ever need this route.

**Comment by neiljerram** [comment] 2015-04-28 08:25
By the way @fasaxc I'm pretty sure that the right person for this is me.  Will discuss prioritizing this in this morning's scrum.

**Comment by Lukasa** [comment] 2015-04-28 09:15
@lwr20 The neutron-dhcp-agent creates the route, not us.

I'm also not quite so sure about this 'never ever' stuff. I believe that some DHCP actions (e.g. renewal) are unicast to the DHCP router's IP address. I'm not entirely familiar with dnsmasq's code, but it'd be good to know whether or not that's a problem.

**Comment by neiljerram** [comment] 2015-04-28 11:30
After checking the DHCP agent code and logs, I can confirm that the route is created automatically by the kernel, when the interface is created and given an address, and not by any explicit 'ip route' command.  This is also borne out by the 'proto kernel' in the 'ip route' output; 'proto kernel' means 'route installed by the kernel'.

So, can we prevent Linux from doing that?  I've looked at sysctl settings, and found nothing there.  Planning next to look at the Linux source code.

**Comment by neiljerram** [comment] 2015-05-05 15:10
Addressed by https://github.com/Metaswitch/calico-neutron/pull/5

**Closed** 2015-05-06 15:28 UTC
Labels: bug
