### ISSUE TITLE
Felix logs aggressively.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#116] opened 2015-01-16 11:16 UTC
I know we like logging, but this might be a little much:

```
2015-01-16 10:40:53,091 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap90053f70-f8
2015-01-16 10:40:53,091 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap89b90c7d-38
2015-01-16 10:40:53,105 [INFO] calico.felix.fsocket 151: Received ENDPOINTUPDATED(89b90c7d-3829-47d8-8b85-6dcede0076d6) on socket EP REP
2015-01-16 10:40:53,105 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap89b90c7d-38
2015-01-16 10:40:53,105 [INFO] calico.felix.fsocket 108: Sent ENDPOINTUPDATED response on socket EP REP
2015-01-16 10:40:53,105 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap90053f70-f8
2015-01-16 10:40:53,106 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap89b90c7d-38
2015-01-16 10:40:53,205 [INFO] calico.felix.fsocket 151: Received ACLUPDATE(1e24b52a-2998-4ebd-bd18-bf8f271ff88e) on socket ACL SUB
2015-01-16 10:40:53,538 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap90053f70-f8
2015-01-16 10:40:53,538 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap89b90c7d-38
2015-01-16 10:40:53,540 [INFO] calico.felix.fsocket 151: Received ACLUPDATE(90053f70-f8f5-4fb1-a5e5-5d7bf5eb63a2) on socket ACL SUB
2015-01-16 10:40:53,540 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap90053f70-f8
2015-01-16 10:40:53,544 [ERROR] calico.felix.endpoint 125: Unable to configure non-existent interface tap89b90c7d-38
```

Some of these duplicate logs are raised at literally the same instant. We can probably be a bit quieter than that.

**Comment by plwhite** [comment] 2015-01-19 09:37
The "Unable to configure" stuff is an artefact of bug #22.

Also part of the problem is that the docker demo plugin is a bit dumb; it just throws config over the wall continuously, and so generates ludicrous amounts of logging

Equally, logging every single keepalive is madness.

**Comment by neiljerram** [comment] 2015-01-19 12:18
FYI the endpoint plugin is slightly less dumb now, following my changes from https://github.com/Metaswitch/calico-docker-prototype/commit/05a996ef490bcf1844e0cd77b51877711c5f2c5f to https://github.com/Metaswitch/calico-docker-prototype/commit/e13067212db9c01bffb8fbdd62ade9051a276143.  It now only only resends ENDPOINTCREATED messages when the config actually changes.

(Also note that the endpoint plugin's other mechanism for periodically resending ENDPOINTCREATED requests has been rendered ineffective by recent changes to heartbeat intervals.)

**Comment by Lukasa** [comment] 2015-01-19 15:11
@plwhite This was not seen on a docker system, it's seen on an OpenStack one.

The issue here is timing: if nova hasn't created the interface yet, Felix seems to spin in an insanely tight loop generating tons of logs.

**Comment by plwhite** [comment] 2015-01-19 16:20
Yes - that is exactly issue #22. When we fix that, those logs go away.

**Comment by neiljerram** [comment] 2015-02-23 16:07
Is this really a bug?  I'm not sure it's helpful for this to be included if I'm looking for a list of all remaining bugs.

**Comment by plwhite** [comment] 2015-02-23 17:12
I think we ought to fix it by setting default log level to `info` and think hard about what logs we really need, but no, I do not see the point of this bug particularly, so I would be happy to close it.

@Lukasa, what do you think?

**Comment by Lukasa** [comment] 2015-02-23 17:29
My concern is that the specific log spam highlighted is clearly indicative of an inefficiently in Felix. Beyond that, I'm happy to raise the default log level and call this closed.

**Comment by matthewdupre** [comment] 2015-06-05 10:56
Default log level is now info - we'll identify any performance issues by profiling it under load.  Closing.

**Closed by matthewdupre** 2015-06-05 10:56 UTC
Labels: bug, felix
