### ISSUE TITLE
RHEL 6.5 install issues.

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#455] opened 2015-04-24 07:34 UTC
suid isn't available on RHEL 6.5. I removed it (do we need to run it as etcd?). Also, the directory give is wrong. My /etc/init/etcd.conf on control node is (also nee similar changes for compute):

```
[root@calico-rh04 ~]# cat /etc/init/etcd.conf
description "etcd"
author "etcd maintainers"

start on stopped rc RUNLEVEL=[2345]
stop on runlevel [!2345]

respawn

script

        env ETCD_DATA_DIR=/var/lib/etcd
        export ETCD_DATA_DIR

        exec /usr/local/bin/etcd --name  calico-rh04                                                        \
                           --advertise-client-urls "http://172.18.203.104:2379,http://172.18.203.104:4001" \
                           --listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001              \
                           --listen-peer-urls http://0.0.0.0:2380                                    \
                           --initial-advertise-peer-urls "http://172.18.203.104:2380"                \
                           --initial-cluster-token calicorh6                                         \
                           --initial-cluster calico-rh04=http://172.18.203.104:2380                  \
                           --initial-cluster-state new
end script
```

**Comment by DaveLangridge** [comment] 2015-04-24 07:43
I can't install libffi-devel - its not available from the repos setup so far. I tried rpmforge ( https://gist.github.com/rderoldan1/5920539 ) with el5 replaced with el6 and it still failed.

**Comment by Lukasa** [comment] 2015-04-24 08:10
Ugh.

We don't *need* to run etcd as a non-privileged user, but it makes me sad to just run everything as root. At this point though RHEL 6.5 is kinda forcing my hand, so we can remove it.

The `libffi-devel` requirement is a weird one. We need it because python-etcd depends on PyOpenSSL, but we don't actually need PyOpenSSL here (because we aren't using SSL at any point). Which is kinda crappy.

**Comment by DaveLangridge** [comment] 2015-04-24 15:23
Solution for libffi-devel:
Enable Redhat repository Optional subchannel as follows:
•	Search /etc/yum.repos.d for the string ‘rhel-6-server-optional-rpms’
•	In the ‘rhel-6-server-optional-rpms’ section change the enable = value from 0 to 1
•	Run ‘yum list libffi-devel’ – to verify the package is now seen (investigate if not)
•	Run ‘yum install libffi-devel’

**Comment by DaveLangridge** [comment] 2015-04-24 15:32
The plugin is hitting exceptions:
2015-04-24 16:14:54.001 1464 ERROR calico.openstack.mech_calico [-] Exception in periodic resync thread
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico Traceback (most recent call last):
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/calico/openstack/t_etcd.py", line 88, in periodic_resync_thread
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     self.provide_felix_config()
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/calico/openstack/t_etcd.py", line 333, in provide_felix_config
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     prefix = self.client.read(iface_pfx_key).value
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/python_etcd-0.3.3_calico_2-py2.6.egg/etcd/client.py", line 349, in read
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     timeout=timeout, check_cluster_uuid=check_cluster_uuid)
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/python_etcd-0.3.3_calico_2-py2.6.egg/etcd/client.py", line 610, in api_execute
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     return self._handle_server_response(response)
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/python_etcd-0.3.3_calico_2-py2.6.egg/etcd/client.py", line 626, in _handle_server_response
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     etcd.EtcdError.handle(**r)
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.6/site-packages/python_etcd-0.3.3_calico_2-py2.6.egg/etcd/__init__.py", line 193, in handle
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico     raise exc(msg, payload)
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico UnboundLocalError: local variable 'payload' referenced before assignment
2015-04-24 16:14:54.001 1464 TRACE calico.openstack.mech_calico

**Comment by DaveLangridge** [comment] 2015-04-24 15:39
Calico felix doesn't start:
Traceback (most recent call last):
  File "/usr/bin/calico-felix", line 9, in <module>
    load_entry_point('calico==0.16', 'console_scripts', 'calico-felix')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/calico/felix/felix.py", line 33, in <module>
    from calico.felix.fiptables import IptablesUpdater
  File "/usr/lib/python2.6/site-packages/calico/felix/fiptables.py", line 30, in <module>
    from gevent import subprocess
ImportError: cannot import name subprocess

I checked, and I do have python-gevent installed:
 yum list python-gevent
Loaded plugins: product-id, security, subscription-manager
Installed Packages
python-gevent.x86_64                                                            0.13.8-3.el6                                                            @epel

**Comment by Lukasa** [comment] 2015-04-24 15:47
Well the subprocess thing is going to be a problem. `gevent.subprocess` was added in gevent 1.0, which it looks like RHEL 6.5 does not have.

**Comment by matthewdupre** [comment] 2015-04-28 14:30
The installed python-gevent can be upgraded to a suitable version by running `yum install python-pip`, `pip install gevent --upgrade`.  Felix then proceeds further before hitting the same bug as the plugin.

**Comment by matthewdupre** [comment] 2015-04-28 14:33
The immediate plugin (and Felix, given a suitable gevent) problem is a bug in python-etcd - __init__.py:handle references the undefined payload if the .format() fails.

This hides an underlying issue though - when a read is issued for a non-existent key, an `etcd.EtcdException: Unable to decode server response` exception is emitted.

**Comment by matthewdupre** [comment] 2015-04-28 15:37
The python-etcd issue is caused by it not properly supporting python 2.6.  See https://github.com/Metaswitch/python-etcd/issues/4.

**Comment by matthewdupre** [comment] 2015-04-28 15:37
EL6 comes with ipset v6.11, which doesn't support -file (EL7 uses v6.19).

`FailedSystemCall: Failed system call (retcode : 2, args : ('ipset', 'restore', '-file', '/tmp/tmplxoZzh'))
  stdout  :
  stderr  : ipset v6.11: Unknown argument -file`

**Comment by matthewdupre** [comment] 2015-04-28 15:48
The ipset issue can be resolved by installing v6.19 by running `rpm -Uvh` on the 2 rpms linked below:

http://rpm.pbone.net/index.php3/stat/4/idpl/23986399/dir/redhat_el_6/com/libipset3-6.19-32.1.x86_64.rpm.html
http://rpm.pbone.net/index.php3/stat/4/idpl/23986390/dir/redhat_el_6/com/ipset-6.19-32.1.x86_64.rpm.html

**Comment by matthewdupre** [comment] 2015-04-28 15:49
There's also an iptables issue (this is a regression from zmq Felix) - v1.4.7 (installed) doesn't support --wait.  The right thing to do is probably just not pass it.

**Comment by matthewdupre** [comment] 2015-04-28 15:59
Removing the --wait flag from the (single) call that uses it fixes this - ipsets are programmed and everything seems shiny.

**Comment by neiljerram** [comment] 2015-04-28 16:09
IIRC, --wait is needed to allow multiple (green) threads to (successfully) program iptables at the same time.

**Comment by matthewdupre** [comment] 2015-04-28 16:24
There was a lot of discussion about this at the time, involving it not doing quite what it suggested anyway, I suggest finding the older issues.

**Comment by neiljerram** [comment] 2015-04-28 16:27
So why was --wait still there then?

But I don't want to be a pain here, because this isn't something that I've paid close attention to.  Just trying to flag something in case it was important and had been forgotten...

**Comment by fasaxc** [comment] 2015-05-20 18:17
Tagging this with 0.21 just to give it a label.  Please triage before 0.21.

**Comment by ed-harrison** [comment] 2015-05-21 08:24
At the moment, we're waiting for someone to confirm that they actually need RHEL 6.5 support - until we get that confirmation, we're not going to proactively fix our RHEL 6.5 code/instructions.  @fasaxc Have you any evidence that RHEL 6.5 is required by any of your contacts or were you just flagging this so that all our issues were labelled?

**Comment by fasaxc** [comment] 2015-05-21 16:02
The latter, just forcing us to triage so it didn't get lost.

**Comment by ed-harrison** [comment] 2015-05-22 08:21
Closing this as we currently have no active plans to resurrect RHEL 6.5 support.

**Closed by ed-harrison** 2015-05-22 08:21 UTC
Labels: docs, install, wontfix

**Comment by matthewdupre** [comment] 2015-12-15 10:50
python-etcd 0.4.3 doesn't work on python 2.6.  0.4.2 works: there's also a 0.4.2+calico version we made with some better logging that works.

**Comment by matthewdupre** [comment] 2015-12-15 10:59
Since #946 removes our unit testing of Python 2.6, there's some more risk that the code itself drifts away from being 2.6 compatible.  This shouldn't be too difficult to get running again (with old python-etcd) if needed: the differences in other packages are more scary.

Note that Red Hat will support OSP 5 (the last one that supports RHEL 6) until June 2017.
