### ISSUE TITLE
felix and plugin communication fails

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#178] opened 2015-02-10 10:07 UTC
felix/plugin can get into a state where felix repeatedly times out:

2015-02-10 08:26:25,334 [ERROR] calico.felix.felix 607: Timed out remote entity : plugin (bound socket *:9902, EP REP)
2015-02-10 08:26:25,336 [INFO] calico.felix.felix 174: Do total resync - ID : 72f0933e-2d8a-44e3-9436-5aff02954825
2015-02-10 08:26:25,336 [INFO] calico.felix.fsocket 173: Sent RESYNCSTATE(72f0933e-2d8a-44e3-9436-5aff02954825) on socket EP REQ

And the plugin fails to connect:

2015-02-10 08:26:25,334 [ERROR] calico.felix.felix 607: Timed out remote entity : plugin (bound socket *:9902, EP REP)
2015-02-10 08:26:25,336 [INFO] calico.felix.felix 174: Do total resync - ID : 72f0933e-2d8a-44e3-9436-5aff02954825
2015-02-10 08:26:25,336 [INFO] calico.felix.fsocket 173: Sent RESYNCSTATE(72f0933e-2d8a-44e3-9436-5aff02954825) on socket EP REQ

Full diags for controller (calico-rh01) here: https://transfer.sh/jPdCl/2015-02-10-09-43-19.gz
And compute (calico-rh02) here: https://transfer.sh/1aVqIz/2015-02-10-09-41-55.gz

The problem starts at about 17:11 (on the 9th), when I'm migrating VMs

**Comment by DaveLangridge** [comment] 2015-02-10 10:08
Restarting calico-felix on calico-rh02 cleared the problem.

**Comment by plwhite** [comment] 2015-02-10 10:57
Looks like Felix is just not getting any data on its EP REP socket - even though the plugin is trying to send them. The plugin seems to periodically send an ENDPOINT request that fails (and is so logged), but never sends heartbeats.

My guess here is that the plugin has a bad connection to Felix, and that the plugin is failing to tear down and recreate the socket.

    2015-02-10 09:01:08.393 1127 INFO calico.openstack.mech_calico [req-64fffb09-b63c-4674-bd60-16519457edc4 None] Felix-HEARTBEAT [calico-rh02]: sleep till time for next heartbeat
    2015-02-10 09:01:08.396 1127 INFO calico.openstack.mech_calico [req-db9bff0d-4f5c-4436-bd03-927439ce99e3 None] Prepared request: {'mac': u'fa:16:3e:0f:ba:f1', 'addrs': [{'properties': {'gr': False}, 'addr': u'192.168.0.54', 'gateway': u'192.168.0.1'}], 'endpoint_id': u'e4954b2c-32b8-4fcb-aea2-4864b64627f5', 'issued': 1423558868389.362, 'resync_id': u'ce1ed4a5-3a3b-437d-9f4a-aeacacba1411', 'type': 'ENDPOINTCREATED', 'state': 'enabled'}
    2015-02-10 09:01:08.396 1127 INFO calico.openstack.mech_calico [req-db9bff0d-4f5c-4436-bd03-927439ce99e3 None] Request sent
    2015-02-10 09:01:10.399 1127 ERROR calico.openstack.mech_calico [req-db9bff0d-4f5c-4436-bd03-927439ce99e3 None] Exception receiving ENDPOINT* response from Felix
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico Traceback (most recent call last):
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/site-packages/calico/openstack/mech_calico.py", line 431, in send_endpoint
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico     rsp = sock.recv_json(zmq.NOBLOCK)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 399, in recv_json
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico     msg = self.recv(flags)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/site-packages/eventlet/green/zmq.py", line 321, in recv
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico     msg = _Socket_recv(self, flags, copy, track)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "socket.pyx", line 628, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5422)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "socket.pyx", line 662, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5241)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1710)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5725)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico Again: Resource temporarily unavailable
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico 
    2015-02-10 09:01:10.399 1127 ERROR calico.openstack.mech_calico [req-db9bff0d-4f5c-4436-bd03-927439ce99e3 None] Exception in Felix-facing ROUTER socket thread
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico Traceback (most recent call last):
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/site-packages/calico/openstack/mech_calico.py", line 294, in felix_router_thread
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico     db_context)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/site-packages/calico/openstack/mech_calico.py", line 439, in send_endpoint
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico     raise FelixUnavailable(op, port['id'], hostname)
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico FelixUnavailable: Failed to create port e4954b2c-32b8-4fcb-aea2-4864b64627f5 because unable to contact Felix at calico-rh02
    2015-02-10 09:01:10.399 1127 TRACE calico.openstack.mech_calico

**Comment by neiljerram** [comment] 2015-02-10 12:37
I see two possibilities here.

1) The plugin is sending on the correct socket to Felix (on calico-rh02), and Felix is just too slow to process and respond to the request.

2) The plugin is sending on the wrong socket to Felix - probably an old one that Felix is no longer reading.

@plwhite - your comment above seems to say that you think it's (2).  Do we have firm evidence to support that?

Also, how sure are you regarding heartbeats?  Expectation is for the plugin to send a heartbeat only every 30s, so there's nothing obviously wrong with not seeing that in the log fragment above.

**Comment by plwhite** [comment] 2015-02-10 12:43
The logs cover quite a long period - I just cut and pasted the only interesting looking bit I found.

I have no firm evidence, but I do know that Felix is sitting around not receiving anything on the socket. Either Felix has got confused and is ignoring messages, or nothing has been sent, or the messages are disappearing.

**Comment by neiljerram** [comment] 2015-02-12 18:16
I've been following through the logs above, and the corresponding code, and seeing quite a few things to improve on the plugin side - will write further about those in a following comment.

However I think I've just found the main problem, on the Felix side: Felix does not rebind the EP REP socket after it times out, because RESTART_TYPES does not include TYPE_EP_REP.  Hence, if the EP REP socket ever times out, communication between Felix and the plugin is never reestablished.

@plwhite - if you have a moment, would appreciate your view on whether this diagnosis is correct, and what the best fix would be.

**Comment by plwhite** [comment] 2015-02-12 18:29
That's deliberate. The bind end does not need to rebind (and may in fact crash when attempting to rebind if the socket is not freed up yet). 

In other words, if the connection goes bad, the listening end can just continue to listen, and the connecting end must reconnect.

Having said that, this is a relatively recent change, covered in the fix to bug #97. I'm open to being persuaded that that fix was misguided!

**Comment by neiljerram** [comment] 2015-02-12 18:33
Some other interim observations, on possible improvements to the plugin code....

- When the plugin does not get a response from Felix within its allowed timeout, it should detect the "Again: Resource temporarily unavailable" exception and log that meaningfully as "Did not get a response from Felix within the allowed timeout", instead of logging the exception and a stack trace.

- The plugin should try to re-establish its outbound connection to Felix on receipt of a HEARTBEAT from Felix, as well as on receipt of a RESYNCSTATE request - because receiving a HEARTBEAT indicates that Felix is there.  However this will require a little careful state, because the HEARTBEAT message does not include the Felix hostname to connect out to.  The state needed is mapping {from 0MQ-connection-ID to hostname}, for each Felix-initiated connection that has delivered a RESYNCSTATE request.

- As noted in other issues, we need to stop logging binary characters for 0MQ connection ID (aka 'peer').

- Each distinct green thread in mech_calico.py should log with a consistent prefix that identifies the thread.  Currently they don't, and it's difficult to tell what is what.

- The thread for sending HEARTBEATs to Felix is currently per-hostname, and I wonder if it should be per-connection instead?

**Comment by neiljerram** [comment] 2015-02-12 19:06
@plwhite - Thanks, what you say above makes sense, so that's not the problem after all.

Earlier I raised https://github.com/Metaswitch/calico/issues/192.  I thought that that wasn't enough of a problem on its own and so have been continuing to look for more things - but I've just realized that that is in fact the whole problem here.  Because a REP socket requires strictly interleaved requests and responses, and so the problem is precisely that Felix missed sending the ENDPOINTDESTROYED response.  Following that, the REP socket will not deliver any newly received requests up to the application (Felix).

**Comment by plwhite** [comment] 2015-02-18 11:17
Does that mean that this bug is fixed by bug #192? I agree that if Felix fails to send anything in response to a request that it receives, then we have a problem - but it should never do that (short of further code bugs like #192). I think it is OK for us not to close and recreate the REP socket on error because the worst case here is that we have received and not yet sent a response when the socket fails, and if that happens we just send a response into nowhere.

**Comment by neiljerram** [comment] 2015-02-18 11:45
Yes, I believe this is now fixed by #192‎.In addition there are some plugin improvements that I'd like to make, listed above in this issue. I have work in progress for those.

**Comment by neiljerram** [comment] 2015-02-21 16:49
The first bullet, in the list above of further plugin improvements, is addressed by https://github.com/Metaswitch/calico/pull/211.

**Comment by neiljerram** [comment] 2015-02-23 16:02
I've moved other possible plugin improvements to https://github.com/Metaswitch/calico/issues/213, and will now close this issue.

**Closed by neiljerram** 2015-02-23 16:02 UTC
